version: '3.5'
services:
  fpm:
    build: docker/dockerfiles/fpm
    restart: always
    depends_on:
      - percona
    volumes:
      - ./bin:/srv/www/bin
      - ./config:/srv/www/config
      - ./data:/srv/www/data
      - ./public:/srv/www/public
      - ./src:/srv/www/src
      - ./vendor:/srv/www/vendor
    networks:
      mynet:
        aliases:
          - fpm.mynet
  nginx:
    build: docker/dockerfiles/nginx
    restart: always
    depends_on:
      - fpm
    ports:
      - "1080:80"
    environment:
      PORT: 80
      FPM_URL: fpm.mynet:9000
    networks:
      mynet:
        aliases:
          - nginx.mynet
  percona:
    image: mysql:8
    environment:
      MYSQL_ROOT_PASSWORD: Qwerty1!
      MYSQL_DATABASE: documents
    ports:
      - "3306:3306"
    networks:
      mynet:
        aliases:
          - percona.mynet
networks:
  mynet:
    external:
      name: mynet
